spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

blogAdmin:
  login: admin
  pass: admin

site:
  url: http://localhost:8080
